### PR TITLE
Fixed wrong return value from getTranslations:  Observable<any> inste…

### PR DESCRIPTION
**Pull request by CodeAndWeb**
Return type should be  Observable<any> as defined in TranslateLoader, not any.

### CODE REVIEW

**Review by ocombe — CHANGES_REQUESTED** [review]
True, but if we do that we need to add rxjs as a peer dependency

**Comment by CodeAndWeb** [comment]
Well... it *is* a peer dependency, isn't it?

**Comment by ocombe** [comment]
it is a transitive dependency since we require ngx translate core which requires rxjs, but it's not a direct dependency: https://github.com/ngx-translate/http-loader/blob/master/lib/package.json#L21-L25

**Comment by CodeAndWeb** [comment]
Yes.. but `TranslateLoader` defines the interface as `public getTranslation(lang: string): Observable<any>`. Implementing it with `public getTranslation(lang: string):any` violates that interface contract.

It's just that Typescript and tslint do not seem to care about it - at least not in the current version.

**Pull request closed without merging**
