### PR TITLE
feat(deps): upgrade to Angular v9

### PR DESCRIPTION
**Pull request by damingerdai**
build(deps): upgrade angular 9.1.1

### CODE REVIEW

**Comment by ocombe** [comment]
Hello, thanks for the PR!
Could you change the installation guidelines to say that v5 is for Angular 9+? (https://github.com/ngx-translate/http-loader#installation)
Thanks!

**Comment by damingerdai** [comment]
> Hello, thanks for the PR!
> Could you change the installation guidelines to say that v5 is for Angular 9+? (https://github.com/ngx-translate/http-loader#installation)
> Thanks!

it is my pleasure. but i need some time

**Comment by damingerdai** [comment]
@ocombe 
please review. thanks

**Comment by reymav** [comment]
Hello, when will you be able to publish this update? @ocombe , @damingerdai

**Comment by damingerdai** [comment]
> Hello, when will you be able to publish this update? @ocombe , @damingerdai

i have no permission to publish

**Review by ocombe — APPROVED** [review]

**Pull request merged**
