### PR TITLE
Fix loading of translations when base-href is set

### LINKED ISSUE #11: Loader does not work with base-href set
When having a base-href set, the loader ignores it and can't fetch the i18n files. 

Example: 
`"build": "ng build --aot --prod --base-href /somestring/",`

All requests are ignoring the base-href: "/assets/i18n/en.json" instead of "/somestring/assets/i18n/en.json".
Adding a dot to the prefix ("./assets/i18n/") fixes the problem.

### PR DESCRIPTION
**Pull request by joachimprinzbach**
Closes #11

### CODE REVIEW

**Comment by ocombe** [comment]
Doesn't it cause trouble when you use the router in html5 mode?
Let's say that you navigate to http://localhost/route1, then it will try to load from http://localhost/route1/assets/i18n/ and fail

**Comment by joachimprinzbach** [comment]
For me it works fine, even with the router in html5 mode.

**Comment by ocombe** [comment]
did you try to reload your app from one of those paths? if it loaded the translations when you were at the root, of course it should still work when you navigate

**Comment by joachimprinzbach** [comment]
Yeah I tried it - it does work ;-)

**Comment by joachimprinzbach** [comment]
Have a look at this repo (branch http-loader)
https://github.com/joachimprinzbach/cli-project/tree/http-loader
You can reload the app from every path (either "home" or "profile") - language files get fetched correctly.

**Comment by ocombe** [comment]
Sorry but I had to revert because it fails the tests, can you make them pass and then I'll merge it.

**Comment by buehler** [comment]
This is a heavy issue

**Comment by buehler** [comment]
Still "broken" :-) just ran into the problem

**Pull request merged**
